### ISSUE TITLE
anyone can put domesticated wolves to sit and stand.

### ISSUE THREAD

**Issue by morottao** [Draylar/wolves-with-armor#2]
I was playing on a server with my friend and he could put my dog to get up and sit down (I have 98 mods installed, I don't know if this is it).

**Comment by Draylar** [comment]
My mod doesn't do anything related to the actual sitting of wolves, so I'm guessing it's [this issue](https://bugs.mojang.com/browse/MC-167561). I'll keep this open just until we know 1.16 solves it. Thanks!

**Comment by morottao** [comment]
was the outdated fabric
