### ISSUE TITLE
Game crash when testing several mods, spawning wither in an enclosed space with several dogs in netherite armor

### ISSUE THREAD

**Issue by rustedgoldmc** [Draylar/wolves-with-armor#25]
I was testing mods together for use on a server I plan to help make. A mod I have installed, the Rat's Mischief mod, is able to take down a wither ridiculously quickly. I decided to test whether the dogs in netherite armor could also take down a wither. I turned off mob griefing so nothing could escape and spawned a wither in a roughly 16x16x8 glass container with about ten dogs (all in netherite armor) in it and as soon as the wither made the preliminary explosion the game crashed. The other mod that is most likely affecting this is the Respawnable Pets mod, which allows mobs you own to respawn and keep their inventory once you sleep. The crash error code was "The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity
Exit Code: -1". I tested it again with only six dogs and it worked without crashing, but then tried with all of them another time and it crashed again. I can kill dogs I own that are in netherite armor just fine, for some reason it is just this specific scenario.
[crash-2021-05-10_01.29.04-server.txt](https://github.com/Draylar/wolves-with-armor/files/6450049/crash-2021-05-10_01.29.04-server.txt)
[crash-2021-05-10_01.41.32-server.txt](https://github.com/Draylar/wolves-with-armor/files/6450050/crash-2021-05-10_01.41.32-server.txt)
Those are the two crash reports generated. My apologies if I've given a load of unnecessary information, I know absolutely nothing about coding and what info is necessary and I figured it would be better to give too much information than too little. I do have other mods installed. Thank you! Lovely mod, by the way - the dogs look great.

**Comment by Draylar** [comment]
This log does not mention Wolves; seems like Rat's Mischief entities are dying and [Respawnable Pets is retrieving an NBT tag that does not exist on them](https://github.com/MoriyaShiine/respawnable-pets/blob/b1866971c6028a5ffce8a39c2bc3c650ca2816c5/src/main/java/moriyashiine/respawnablepets/mixin/LivingEntityMixin.java#L101). I see you already opened an issue on their side, so I will tag them as well to add this info: [#29](https://github.com/MoriyaShiine/respawnable-pets/issues/29)

Happy to hear you like the mod :)
