### ISSUE TITLE
Wolf armor on Server

### ISSUE THREAD

**Issue by lucasfelipe-sh** [Draylar/wolves-with-armor#3]
I'm playing in a server, it's not lan mode.
We all are playing with the same version an the server has the same mod, so my friend, me and the server has the mod installed.
When she put and armor on her wolf, it not shows me the wolf weared.
She can't see when wear my Wolf too.
But, when I restart the server, the armor appears.

**Comment by Draylar** [comment]
I just pushed a new change in 1.1.0: you now can click on wolves directly to add armor, and shift click to take it off. There is no longer any UI. This change should also fix this sync issue. Thanks for the report!
