### ISSUE TITLE
Wolf armor item exists in creative menu but disappears when thrown and cannot be put on a wolf or crafted (fabric 1.16.5 server)

### ISSUE THREAD

**Issue by helloeverything1** [Draylar/wolves-with-armor#36]
I had some issues with the newest version of fabric api so I switched to version 0.33.1 and my game stopped crashing when connecting to the server but now the wolf armor seems to only exist in the creative menu.

**Comment by Draylar** [comment]
Sounds like you (potentially) don't have the mod on the server as well - if you experience this issue again, please let me know and I will help you figure it out. :)
