### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by RaoqTheWiz** [Draylar/wolves-with-armor#42]
This mod causes game to go to safe mode 1.18.2. I cannot play any new worlds or load existing worlds with the 1.18.1 mod.

**Comment by Perchycs** [comment]
Yeah have the same issue on 1.18.2

**Comment by mkehoe28** [comment]
I am having the same issue. Been using the same world for a few months now and the only thing that changes was me adding this mod. Removing the mod and the world worked fine. Same issue when trying to create new worlds.

**Comment by Draylar** [comment]
Releasing a 1.18.2 update in a second... thank you for the report!
