### ISSUE TITLE
Can I have cat armor too?

### ISSUE THREAD

**Issue by imax9000** [Draylar/wolves-with-armor#46]
Pleeeeease...

**Comment by LinkelinIsMyName** [comment]
Have you found a cat armor mod?

**Comment by IMB11** [comment]
I'll consider this in Armorful, a 1.20/1.20.1 continuation of this mod essentially. 

I am working on a 1.19 backport.

https://modrinth.com/mod/armorful

**Comment by Draylar** [comment]
I had an idea for a mod called "Nine Lives," which would be the Cat version of Wolves with Armor. I would totally make it if somebody supplies me with Cat Armor textures!😆
