### ISSUE TITLE
[sugestion] Add enderite armor <3

### ISSUE THREAD

**Issue by CosmicCow** [Draylar/wolves-with-armor#6]
https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-fabric

**Comment by Draylar** [comment]
I recently added support for my [Static Content](https://github.com/Draylar/static-content) library to this mod, which means Enderite Mod can add Wolf Armor if they want to (see how I do it [here](https://github.com/Draylar/wolves-with-armor/tree/1.16/src/main/resources/static_data/wolveswitharmor/wolf_armor)), as long as they ship textures / resources alongside it.
